<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5VHKQUJ" failures="1" tests="1" name="com.ae.qa.testcasesTenantAdmin.DataSourcesPageTestTA" time="100.121" errors="0" timestamp="2023-04-29T19:10:11 IST" skipped="0">
  <testcase classname="com.ae.qa.testcasesTenantAdmin.DataSourcesPageTestTA" name="validateCreateDataSourcePostgresTest" time="100.121">
    <failure message="Test Connection failed expected [Test Connection Successful] but found [Can&#039;t create connection for dataSource vae]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test Connection failed expected [Test Connection Successful] but found [Can't create connection for dataSource vae]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.ae.qa.pagesTenantAdmin.DataSourcesPageTA.validateCreateDataSourcePostgres(DataSourcesPageTA.java:90)
at com.ae.qa.testcasesTenantAdmin.DataSourcesPageTestTA.validateCreateDataSourcePostgresTest(DataSourcesPageTestTA.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- validateCreateDataSourcePostgresTest -->
  <system-out>
    <![CDATA[User LogIn Succesfully
Report tab clicked
DataSource  tab clicked
Data-Source Form opened
Button Clicked]]>
  </system-out>
</testsuite> <!-- com.ae.qa.testcasesTenantAdmin.DataSourcesPageTestTA -->
